require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TalentsController do

  # This should return the minimal set of attributes required to create a valid
  # Talent. As you add validations to Talent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all talents as @talents" do
      talent = Talent.create! valid_attributes
      get :index
      assigns(:talents).should eq([talent])
    end
  end

  describe "GET show" do
    it "assigns the requested talent as @talent" do
      talent = Talent.create! valid_attributes
      get :show, :id => talent.id.to_s
      assigns(:talent).should eq(talent)
    end
  end

  describe "GET new" do
    it "assigns a new talent as @talent" do
      get :new
      assigns(:talent).should be_a_new(Talent)
    end
  end

  describe "GET edit" do
    it "assigns the requested talent as @talent" do
      talent = Talent.create! valid_attributes
      get :edit, :id => talent.id.to_s
      assigns(:talent).should eq(talent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Talent" do
        expect {
          post :create, :talent => valid_attributes
        }.to change(Talent, :count).by(1)
      end

      it "assigns a newly created talent as @talent" do
        post :create, :talent => valid_attributes
        assigns(:talent).should be_a(Talent)
        assigns(:talent).should be_persisted
      end

      it "redirects to the created talent" do
        post :create, :talent => valid_attributes
        response.should redirect_to(Talent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved talent as @talent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Talent.any_instance.stub(:save).and_return(false)
        post :create, :talent => {}
        assigns(:talent).should be_a_new(Talent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Talent.any_instance.stub(:save).and_return(false)
        post :create, :talent => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested talent" do
        talent = Talent.create! valid_attributes
        # Assuming there are no other talents in the database, this
        # specifies that the Talent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Talent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => talent.id, :talent => {'these' => 'params'}
      end

      it "assigns the requested talent as @talent" do
        talent = Talent.create! valid_attributes
        put :update, :id => talent.id, :talent => valid_attributes
        assigns(:talent).should eq(talent)
      end

      it "redirects to the talent" do
        talent = Talent.create! valid_attributes
        put :update, :id => talent.id, :talent => valid_attributes
        response.should redirect_to(talent)
      end
    end

    describe "with invalid params" do
      it "assigns the talent as @talent" do
        talent = Talent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Talent.any_instance.stub(:save).and_return(false)
        put :update, :id => talent.id.to_s, :talent => {}
        assigns(:talent).should eq(talent)
      end

      it "re-renders the 'edit' template" do
        talent = Talent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Talent.any_instance.stub(:save).and_return(false)
        put :update, :id => talent.id.to_s, :talent => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested talent" do
      talent = Talent.create! valid_attributes
      expect {
        delete :destroy, :id => talent.id.to_s
      }.to change(Talent, :count).by(-1)
    end

    it "redirects to the talents list" do
      talent = Talent.create! valid_attributes
      delete :destroy, :id => talent.id.to_s
      response.should redirect_to(talents_url)
    end
  end

end
